CREATE TABLE location (
    id VARCHAR(36) PRIMARY KEY COMMENT '地点ID',
    user_id VARCHAR(36) NOT NULL COMMENT '关联用户表user.id',
    name VARCHAR(100) NOT NULL COMMENT '地点名称',
    lat DECIMAL(11,7) DEFAULT NULL COMMENT '纬度',
    lng DECIMAL(11,7) DEFAULT NULL COMMENT '经度',
    continent VARCHAR(50) DEFAULT '' COMMENT '大洲',
    country VARCHAR(50) DEFAULT '' COMMENT '国家',
    province VARCHAR(50) DEFAULT '' COMMENT '省份/洲',
    address VARCHAR(255) DEFAULT '' COMMENT '详细地址',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地点表';