spring:
  application:
    name: footPrintMap
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/footprintmap?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 'Q5h8VUxT8))MX>AHky:$'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  flyway:
    enabled: false  # 关闭 Flyway
    baseline-on-migrate: true  # 已有表也能平滑接入
    locations: classpath:db/migration  # SQL 脚本存放路径
#  mybatis-plus:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: f8c3de3d1f6f4d7e8a9b0c1d2e3f4a5b
  expiration: 1800000

mybatis-plus:
  type-aliases-package: zjut.edu.cn.footPrintMap.entity